stages:
  - staging
  # - production
  
staging:
  stage: staging
  script:
    - cp -r ./ /var/www/damirco/frontend-test
    - echo $env_staging | base64 -d > /var/www/damirco/frontend-test/.env
    - cd /var/www/damirco
    - docker-compose up  -d --build frontend-test
  only:
    - master

# production:
#   stage: production
#   script:
#     - cp -r ./ /var/www/damirco/backend
#     - cd /var/www/damirco
#     - docker-compose up  -d --build damirco
#   only:
#     - master